In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris
import plotly.express as px
import plotly.graph_objects as go

import os

# Elemento necesario para kmeans.
os.environ["OMP_NUM_THREADS"] = "1"

In [3]:
data=pd.read_csv("Mall_Customers.csv")
data.head()

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [4]:
data["CustomerID"].value_counts().sort_values(ascending=False)

CustomerID
1      1
2      1
3      1
4      1
5      1
      ..
196    1
197    1
198    1
199    1
200    1
Name: count, Length: 200, dtype: int64

In [5]:
len(data["CustomerID"].unique())

200

In [6]:
print('Shape:', data.shape)
print('type:',type(data))

Shape: (200, 5)
type: <class 'pandas.DataFrame'>

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    str
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), str(1)
memory usage: 7.9 KB

In [8]:
data.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  200.000000          200.000000              200.000000
mean   100.500000   38.850000           60.560000               50.200000
std     57.879185   13.969007           26.264721               25.823522
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   28.750000           41.500000               34.750000
50%    100.500000   36.000000           61.500000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [9]:
data=data.rename(columns={"Annual Income (k$)":"Annual_Income","Spending Score (1-100)":"Spending_Score"})

In [10]:
data.head()

   CustomerID  Gender  Age  Annual_Income  Spending_Score
0           1    Male   19             15              39
1           2    Male   21             15              81
2           3  Female   20             16               6
3           4  Female   23             16              77
4           5  Female   31             17              40

In [11]:
#Annual Income (k$)
#Spending Score (1-100)

In [12]:
experimento=data[["Age","Annual_Income","Spending_Score"]]
experimento.head()

   Age  Annual_Income  Spending_Score
0   19             15              39
1   21             15              81
2   20             16               6
3   23             16              77
4   31             17              40

In [13]:
# 
kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(experimento)
print('type:',type(clusters))
clusters

type: <class 'numpy.ndarray'>

array([2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2,
       0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2, 0, 2,
       0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 2,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1, 3, 1,
       3, 1], dtype=int32)

In [14]:
clusters=pd.DataFrame(clusters)
clusters=clusters.rename(columns={0:"cluster"})

In [15]:
clusters

     cluster
0          2
1          2
2          0
3          2
4          0
..       ...
195        1
196        3
197        1
198        3
199        1

[200 rows x 1 columns]

In [16]:
clusters["cluster"].value_counts()

cluster
0    95
1    39
3    38
2    28
Name: count, dtype: int64

In [17]:
data_total=pd.concat([data,clusters],axis=1)
data_total.head()

   CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
0           1    Male   19             15              39        2
1           2    Male   21             15              81        2
2           3  Female   20             16               6        0
3           4  Female   23             16              77        2
4           5  Female   31             17              40        0

In [18]:
#data_total=data_total["cluster"]+1
data_total["cluster"] = data_total["cluster"] + 1
data_total.shape

(200, 6)

In [19]:
data_total.describe()

       CustomerID         Age  Annual_Income  Spending_Score     cluster
count  200.000000  200.000000     200.000000      200.000000  200.000000
mean   100.500000   38.850000      60.560000       50.200000    2.045000
std     57.879185   13.969007      26.264721       25.823522    1.174681
min      1.000000   18.000000      15.000000        1.000000    1.000000
25%     50.750000   28.750000      41.500000       34.750000    1.000000
50%    100.500000   36.000000      61.500000       50.000000    2.000000
75%    150.250000   49.000000      78.000000       73.000000    3.000000
max    200.000000   70.000000     137.000000       99.000000    4.000000

In [ ]:
# 2+4 = 1 y 3+1 =0

In [20]:
data_total.tail()

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
195         196  Female   35            120              79        2
196         197  Female   45            126              28        4
197         198    Male   32            126              74        2
198         199    Male   32            137              18        4
199         200    Male   30            137              83        2

In [21]:
data_total_1=data_total[data_total["cluster"]==1]
data_total_2=data_total[data_total["cluster"]==2]

data_total_3=data_total[data_total["cluster"]==3]
data_total_4=data_total[data_total["cluster"]==4]

In [22]:
data_total_1

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
2             3  Female   20             16               6        1
4             5  Female   31             17              40        1
6             7  Female   35             18               6        1
8             9    Male   64             19               3        1
10           11    Male   67             19              14        1
..          ...     ...  ...            ...             ...      ...
118         119  Female   51             67              43        1
119         120  Female   50             67              57        1
120         121    Male   27             67              56        1
121         122  Female   38             67              40        1
122         123  Female   40             69              58        1

[95 rows x 6 columns]

In [23]:
print(len(data_total_2))
data_total_2

39

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
123         124    Male   39             69              91        2
125         126  Female   31             70              77        2
127         128    Male   40             71              95        2
129         130    Male   38             71              75        2
131         132    Male   39             71              75        2
133         134  Female   31             72              71        2
135         136  Female   29             73              88        2
137         138    Male   32             73              73        2
139         140  Female   35             74              72        2
141         142    Male   32             75              93        2
143         144  Female   32             76              87        2
145         146    Male   28             77              97        2
147         148  Female   32             77              74        2
149         150    Male   34             78              90        2
151         152    Male   39             78              88        2
153         154  Female   38             78              76        2
155         156  Female   27             78              89        2
157         158  Female   30             78              78        2
159         160  Female   30             78              73        2
161         162  Female   29             79              83        2
163         164  Female   31             81              93        2
165         166  Female   36             85              75        2
167         168  Female   33             86              95        2
169         170    Male   32             87              63        2
171         172    Male   28             87              75        2
173         174    Male   36             87              92        2
175         176  Female   30             88              86        2
177         178    Male   27             88              69        2
179         180    Male   35             93              90        2
181         182  Female   32             97              86        2
183         184  Female   29             98              88        2
185         186    Male   30             99              97        2
187         188    Male   28            101              68        2
189         190  Female   36            103              85        2
191         192  Female   32            103              69        2
193         194  Female   38            113              91        2
195         196  Female   35            120              79        2
197         198    Male   32            126              74        2
199         200    Male   30            137              83        2

In [24]:
data_total_3.head()

   CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
0           1    Male   19             15              39        3
1           2    Male   21             15              81        3
3           4  Female   23             16              77        3
5           6  Female   22             17              76        3
7           8  Female   23             18              94        3

In [25]:
data_total_4.head()

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
124         125  Female   23             70              29        4
126         127    Male   43             71              35        4
128         129    Male   59             71              11        4
130         131    Male   47             71               9        4
132         133  Female   25             72              34        4

In [26]:
data_total_1.describe()

       CustomerID        Age  Annual_Income  Spending_Score  cluster
count   95.000000  95.000000      95.000000       95.000000     95.0
mean    71.831579  44.894737      48.705263       42.631579      1.0
std     33.379396  15.341831      14.522817       14.713616      0.0
min      3.000000  18.000000      16.000000        3.000000      1.0
25%     48.500000  32.000000      40.000000       40.500000      1.0
50%     76.000000  48.000000      54.000000       47.000000      1.0
75%     99.500000  56.000000      61.000000       52.000000      1.0
max    123.000000  70.000000      69.000000       60.000000      1.0

In [27]:
data_total_2.describe()

       CustomerID        Age  Annual_Income  Spending_Score  cluster
count   39.000000  39.000000      39.000000       39.000000     39.0
mean   162.000000  32.692308      86.538462       82.128205      2.0
std     22.803509   3.728650      16.312485        9.364489      0.0
min    124.000000  27.000000      69.000000       63.000000      2.0
25%    143.000000  30.000000      75.500000       74.500000      2.0
50%    162.000000  32.000000      79.000000       83.000000      2.0
75%    181.000000  35.500000      95.000000       90.000000      2.0
max    200.000000  40.000000     137.000000       97.000000      2.0

In [28]:
data_total_3.describe()

       CustomerID        Age  Annual_Income  Spending_Score  cluster
count   28.000000  28.000000      28.000000       28.000000     28.0
mean    28.642857  24.821429      28.714286       74.250000      3.0
std     19.235797   5.571446      10.384665       14.075524      0.0
min      1.000000  18.000000      15.000000       39.000000      3.0
25%     13.500000  20.750000      19.750000       64.000000      3.0
50%     27.000000  23.000000      28.000000       74.000000      3.0
75%     40.500000  30.000000      37.250000       81.250000      3.0
max     69.000000  35.000000      48.000000       99.000000      3.0

In [29]:
data_total_4.describe()

       CustomerID        Age  Annual_Income  Spending_Score  cluster
count   38.000000  38.000000      38.000000       38.000000     38.0
mean   162.000000  40.394737      87.000000       18.631579      4.0
std     22.226111  11.376931      16.271348       10.915947      0.0
min    125.000000  19.000000      70.000000        1.000000      4.0
25%    143.500000  34.000000      76.250000       10.250000      4.0
50%    162.000000  41.500000      80.000000       16.500000      4.0
75%    180.500000  47.000000      96.000000       26.750000      4.0
max    199.000000  59.000000     137.000000       40.000000      4.0

In [30]:
# 2+4 = 1 y 3+1 =0 
data_total

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
0             1    Male   19             15              39        3
1             2    Male   21             15              81        3
2             3  Female   20             16               6        1
3             4  Female   23             16              77        3
4             5  Female   31             17              40        1
..          ...     ...  ...            ...             ...      ...
195         196  Female   35            120              79        2
196         197  Female   45            126              28        4
197         198    Male   32            126              74        2
198         199    Male   32            137              18        4
199         200    Male   30            137              83        2

[200 rows x 6 columns]

In [31]:
# se cambia 2 y 4 por 1.   Y  1 y 3 por 0
data_total["cluster"] = data_total["cluster"].replace({2: 1, 4: 1, 1: 0, 3: 0})
data_total

     CustomerID  Gender  Age  Annual_Income  Spending_Score  cluster
0             1    Male   19             15              39        0
1             2    Male   21             15              81        0
2             3  Female   20             16               6        0
3             4  Female   23             16              77        0
4             5  Female   31             17              40        0
..          ...     ...  ...            ...             ...      ...
195         196  Female   35            120              79        1
196         197  Female   45            126              28        1
197         198    Male   32            126              74        1
198         199    Male   32            137              18        1
199         200    Male   30            137              83        1

[200 rows x 6 columns]